<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Generated by Apache ServiceMix Archetype -->
<xsl:stylesheet
  xmlns:xsl='http://www.w3.org/1999/XSL/Transform'
  version='1.0'>

  <xsl:output method="xml" indent="yes" encoding="ISO-8859-1"/>

  <xsl:template match="/">
    <transformed>
      <xsl:copy>
        <xsl:copy-of select="attribute::*"/>
        <xsl:apply-templates/>
      </xsl:copy>
    </transformed>
  </xsl:template>
  
  <xsl:template match="node() | @*">
    <xsl:copy>
      <xsl:apply-templates select="node() | @*"/>
    </xsl:copy>
  </xsl:template>
  
</xsl:stylesheet>
